import React from 'react';
import './index.css';

import { ReduxProvider, ReactQueryProvider } from '@/providers';

export const metadata = {
  title: 'Nx template',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
